version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-cooking
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: CookingDB
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - cooking_network
networks:
  cooking_network:
    driver: bridge